#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/zz0/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# my changes go here

#setbackground
~/.fehbg

#dockapps slit
wmload -led green -withdrawn -shape&
wmMoonClock -lat 25.4167 -lon 492500&
wmsm -d sda&
wmcpuload -bl -lc rgb:00/cc/ff&
wmitime&
wmMatrix&
wmnd -I wls3&
wmnd -I eth0 -w twisted&
wmbattery&
#wmCalClock -tc purple -bc green -24 -comicsans&
#wmckgmail&

#composer
compton -cCG -i 0.75 -e 0.75 -I 0.1 --active-opacity 0.89 --vsync opengl&

#ScreenSaver AutoLock
xautolock -time 5 -locker 'xlock -mode matrix'&

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/zz0/.fluxbox/log"
