#!/bin/bash
#Scrpit de Registro de Accessos a Internet
#Sarg 2.3.0
#By: isca0
#e-mail --> igorsca(at)gmail.com
##STRBKP##
#
#
stmp=/tmp/sarg
bsarg=/usr/local/bin/sarg
sconf=/usr/local/sarg/sarg-isb.conf
older=/var/www/htdocs/sarg
index=/var/www/htdocs/sarg
monitor=/var/www/htdocs/monitor

#squid global vars
user=squid
group=squid
squid="/usr/local/squid/sbin/squid"
squidlog="/usr/local/squid/var/logs"

#Cores
azul="\033[34;40m"
vermelho="\033[31;40m"
verde="\033[32;40m"
amarelo="\033[33;40;1m"
apaga="\033[0m"
#Funcoes
#___________

limpa(){
rm -rf $older/*

if [ -d $stmp ]
then
	rm -rf $monitor
	rm -rf $stmp
	rm -rf $older/*
else

	rm -rf $monitor
	rm -rf $older/*
fi
}

#-----------

gera(){
echo -e ""$verde"Lendo arquivo "$sconf" para gerar relatorio"$apaga""
"$bsarg" -f "$sconf" 
if [ -d "$index" ]
then	
	ln -sf  "$index" "$monitor"
else
	echo -e ""$vermelho"Nao foi possivel fazer link monitor, "$index" nao foi encontrado"$apaga""
fi
}

#-----------

delog(){
su $user -c "$squid -k rotate"	
rm -rf $squidlog/*.2
}


case "$1" in

clean)
limpa
echo -e ""$verde"Limpeza do Sarg efetuada!"$apaga""
exit
;;

make)
gera
echo -e ""$verde" Relatorio `date` esta pronto."$apaga""
exit
;;

dlog)
delog
echo -e ""$verde" Todos os Logs do Squid estao vazios agora."$apaga""
exit
;;

help)
clear
echo -e "
$0 funciona com as sintaxes: "$amarelo"clean make dlog help"$apaga".

"$amarelo"clean"$apaga" : Limpa os diretorios antigos do Sarg
"$amarelo"make"$apaga"  : Cria um relatorio novo do sarg com base no access.log do squid.
"$amarelo"dlog"$apaga"  : Faz o rotate de logs do squid.
"$amarelo"help"$apaga"  : Exibe essa ajuda.

						Por:"$azul" Igor Brandao"$apaga"
						email:"$verde" igorsca(at)gmail.com"$apaga"
						"
;;

*)
echo -e "\033[32;40mUse clean|make|dlog|help\033[0m"
;;
esac
exit
