#!/bin/sh
#This script is util for manage VMWare Machines from command line
#The main objetive of this script is start machines with headless and restore snapshot's
#
#some documental commands are:
# * vmrun list, vmrun listSnapshots, vmrun revertToSnapshot etc...
mymachine=debian_x64.vmx

case $1 in
-lm)
vmrun list 
;;
-ls)
vmrun listSnapshots $mymachine
;;
-rs)
vmrun revertToSnapshot $mymachine $3
;;
*)
echo use $0 with:
echo "	
	* -lm --> list vm's
	* -ls [machine] --> list Snapshot's
	* -rs [machine, snapshot] --> restore snapshot for machine
"	
exit 0
;;
esac
exit 
